// Ref https://chainid.network/

export interface ChainInfo {
  name: string,
  chainId: number,
  shortName: string,
  chain: string,
  network: string,
  networkId: number,
  nativeCurrency: ChainNativeCurrency,
  rpc: string[],
  faucets: string[],
  explorers?: ChainExplorer[],
  infoURL: string
  slip44?: number;
  icon?: string;
  ens?: { registry: string }
  parent?: {
    chain: string,
    type: string
  }
}

export interface ChainNativeCurrency {
  name: string,
  symbol: string,
  decimals: number
}

export interface ChainExplorer {
  name: string,
  url: string,
  standard: string,
  icon?: string
}

export interface ChainShortInfo {
  name: string;
  chain: string;
}

export const AllChainKeyValue = {
  "Bluzelle": "Bluzelle",
  "ETH": "ETH",
  "EXP": "EXP",
  "ETC": "ETC",
  "TCH": "TCH",
  "UBQ": "UBQ",
  "META": "META",
  "DIODE": "DIODE",
  "FLR": "FLR",
  "TST": "TST",
  "RSK": "RSK",
  "GooD": "GooD",
  "TBWG": "TBWG",
  "VAL": "VAL",
  "TLOS": "TLOS",
  "pangolin": "pangolin",
  "crab": "crab",
  "XDC": "XDC",
  "TXDC": "TXDC",
  "CSC": "CSC",
  "BSC": "BSC",
  "Ontology": "Ontology",
  "EOS": "EOS",
  "GO": "GO",
  "ELLA": "ELLA",
  "okexchain": "okexchain",
  "DBM": "DBM",
  "SOTER": "SOTER",
  "MIX": "MIX",
  "POA": "POA",
  "PC": "PC",
  "GeneChain": "GeneChain",
  "METER": "METER",
  "GTTEST": "GTTEST",
  "GT": "GT",
  "TOMO": "TOMO",
  "XDAI": "XDAI",
  "ETI": "ETI",
  "Web3Games": "Web3Games",
  "TT": "TT",
  "XPR": "XPR",
  "ETL": "ETL",
  "FUSE": "FUSE",
  "DWU": "DWU",
  "FETH": "FETH",
  "Heco": "Heco",
  "Matic(Polygon)": "Matic(Polygon)",
  "PHT": "PHT",
  "EDI": "EDI",
  "Energy Web Chain": "Energy Web Chain",
  "FTM": "FTM",
  "HPB": "HPB",
  "KCC": "KCC",
  "Theta": "Theta",
  "CRO": "CRO",
  "RUPX": "RUPX",
  "TAO": "TAO",
  "mACA": "mACA",
  "KAR": "KAR",
  "ETHERMINT": "ETHERMINT",
  "ACA": "ACA",
  "Haic": "Haic",
  "CLO": "CLO",
  "WAN": "WAN",
  "YETI": "YETI",
  "KLAY": "KLAY",
  "NEW": "NEW",
  "EVC": "EVC",
  "Sakura": "Sakura",
  "Clover": "Clover",
  "MATH": "MATH",
  "MOON": "MOON",
  "Catechain": "Catechain",
  "ATH": "ATH",
  "TSF": "TSF",
  "EGEM": "EGEM",
  "420": "420",
  "EDG": "EDG",
  "Kortho Chain": "Kortho Chain",
  "iotex.io": "iotex.io",
  "ESN": "ESN",
  "RBD": "RBD",
  "MDGL": "MDGL",
  "Kortho": "Kortho",
  "OLO": "OLO",
  "bloxberg": "bloxberg",
  "smartBCH": "smartBCH",
  "smartBCHTest": "smartBCHTest",
  "GEN": "GEN",
  "WEB": "WEB",
  "MINTME": "MINTME",
  "FSN": "FSN",
  "NRG": "NRG",
  "42069": "42069",
  "CELO": "CELO",
  "AVAX": "AVAX",
  "Volta": "Volta",
  "Matic": "Matic",
  "QuarkChain": "QuarkChain",
  "AKA": "AKA",
  "ARTIS": "ARTIS",
  "ETHO": "ETHO",
  "XERO": "XERO",
  "MUSIC": "MUSIC",
  "PEP": "PEP",
  "ILT": "ILT",
  "QKI": "QKI",
  "AUX": "AUX",
  "JOYS": "JOYS",
  "AQUA": "AQUA",
  "TOYS": "TOYS",
  "IPOS": "IPOS",
  "NEAR": "NEAR",
  "Harmony": "Harmony",
  "PIRL": "PIRL",
  "Palm": "Palm"
}
